# Generated by Django 2.0.2 on 2018-05-24 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_nomeCompleto', models.CharField(max_length=2, null=True, verbose_name='código nome')),
                ('nomeCompleto', models.CharField(max_length=120, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=11, null=True)),
                ('sexo', models.CharField(choices=[('MASCULINO', 'masculino'), ('FEMENINO', 'femenino')], default='MASCULINO', max_length=10, verbose_name='Sexo')),
                ('telefone', models.CharField(max_length=20, null=True, verbose_name='Telefone')),
                ('dataNascimento', models.DateField(null=True, verbose_name='Data de Nascimento')),
                ('altura', models.FloatField(null=True, verbose_name='Altura')),
                ('peso', models.FloatField(null=True, verbose_name='Peso')),
                ('IMC', models.FloatField(null=True, verbose_name='IMC')),
                ('observacao', models.TextField(max_length=120, null=True, verbose_name='Anotacoes')),
                ('visivel', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('update_at', models.DateTimeField(auto_now_add=True, verbose_name='Atualizado em')),
            ],
        ),
    ]
