# Generated by Django 2.0.2 on 2018-06-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='nivelAtividade',
            field=models.CharField(choices=[('MUITO_ATIVO', 'MUITO_ATIVO'), ('ATIVO', 'ATIVO'), ('IRREG_ATIVO_A', 'IRREG_ATIVO_A'), ('IRREG_ATIVO_B', 'IRREG_ATIVO_B'), ('SEDENTARISMO', 'SEDENTARISMO')], default='SEDENTARISMO', max_length=20, verbose_name='Nivel Atividade'),
        ),
    ]
