# Generated by Django 2.0.2 on 2018-05-24 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoExame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeExame', models.CharField(max_length=30, verbose_name='Nome do Exame')),
                ('descricao', models.TextField(max_length=1000, null=True, verbose_name='Descricao')),
                ('visivel', models.BooleanField(default=True)),
                ('pontuacao', models.BooleanField(default=False)),
                ('observacao', models.BooleanField(default=True)),
                ('cronometro', models.BooleanField(default=True)),
                ('risco_queda', models.BooleanField(default=False)),
                ('deslocamento', models.BooleanField(default=False)),
                ('pontuacao_soma', models.BooleanField(default=False)),
                ('coleta_dispositivo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('update_at', models.DateTimeField(auto_now_add=True, verbose_name='Atualizado em')),
            ],
        ),
    ]
