# Generated by Django 2.0.2 on 2018-05-24 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paciente', '0001_initial'),
        ('tipoExame', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coleta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_exec', models.PositiveSmallIntegerField(default=0)),
                ('observacao', models.TextField(blank=True, max_length=200, null=True, verbose_name='Observação')),
                ('riscoQueda', models.CharField(blank=True, choices=[('ALTO', 'alto'), ('MEDIO', 'médio'), ('BAIXO', 'baixo')], default='None', max_length=10, null=True, verbose_name='Risco de Queda')),
                ('pontuacao', models.CharField(blank=True, choices=[('0', 0), ('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], default='None', max_length=10, null=True, verbose_name='Pontuacao')),
                ('pontuacao_soma', models.CharField(blank=True, max_length=10, null=True, verbose_name='Pontuacao Soma')),
                ('cronometro', models.CharField(blank=True, max_length=10, null=True, verbose_name='Tempo')),
                ('deslocamento', models.CharField(blank=True, max_length=10, null=True, verbose_name='Deslocamento cm')),
                ('visivel', models.BooleanField(default=False)),
                ('amostras', models.TextField(blank=True, null=True)),
                ('dataCriacao', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('dataModificacao', models.DateTimeField(auto_now_add=True, verbose_name='Atualizado em')),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.Paciente')),
                ('tipoExame', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tipoExame.TipoExame')),
            ],
        ),
    ]
